const router = require('express').Router()
const userCtrl =  require('../controllers/userCtrl')
const auth = require("../middleware/auth")

router.post('/register', userCtrl.register)
router.post('/login', userCtrl.login)
router.get('/logout', userCtrl.logout)
router.get('/refreshToken', userCtrl.refreshToken)
router.get('/info', auth, userCtrl.getUser)
router.post('/roleChange', auth, userCtrl.roleChange)
router.post('/delete', auth, userCtrl.deleteUser)
router.post('/addCart', auth, userCtrl.pushCart)
router.post('/changeCart',auth,userCtrl.changeCart)
router.get('/cookie', userCtrl.cookie)
module.exports = router;